name: Release
on:
  push:
    branches:
      - 'release-test/**'
#      - 'main'
#    tags:
#      - 'v**'

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
#      # Build
#      - name: Build / Check / Code coverage
#        run: ./gradlew build check


#      # Code coverage
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v3
#      # Publish
#      - name: Publish
#        env:
#          USERNAME: ${{ secrets.USERNAME }}
#          TOKEN: ${{ secrets.TOKEN }}
#        run: ./gradlew publish
#      # Docs
#      - name: Dokka Html
#        run: ./gradlew dokkaHtml

      - name: Checkout Docs
        run: |
          git fetch
          git checkout origin/docs
          ./gradlew copyFromDocsToTmp
          git checkout release-test/1
          ./gradlew dokkaHtml

      - name: Commit Docs
        run: |
          git add ./build/dokka/html -f
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Update documentation for $(./gradlew -q printVersion)"
          git push origin release-test/1:docs -f
#      # Deploy GitHub Pages
#      - name: Setup Pages
#        uses: actions/configure-pages@v2
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v1.0.7
#        with:
#          path: './build/dokka/html/'
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1.2.3
